SPECIAL_TOKEN_PRE = "["
SPECIAL_TOKEN_POST = "]"

SPECIAL_TOKENS = {
    "START": f"{SPECIAL_TOKEN_PRE}g_start{SPECIAL_TOKEN_POST}",
    "END": f"{SPECIAL_TOKEN_PRE}g_end{SPECIAL_TOKEN_POST}",
    "UNKNOWN": f"{SPECIAL_TOKEN_PRE}unknown{SPECIAL_TOKEN_POST}",
    "PAD": f"{SPECIAL_TOKEN_PRE}pad{SPECIAL_TOKEN_POST}",
}
